insert into mtPaises (nmPais) values ('--OTHER--');
insert into mtPaises (nmPais) values ('Afghanistan');
insert into mtPaises (nmPais) values ('Albania');
insert into mtPaises (nmPais) values ('Algeria');
insert into mtPaises (nmPais) values ('American Samoa');
insert into mtPaises (nmPais) values ('Andorra');
insert into mtPaises (nmPais) values ('Angola');
insert into mtPaises (nmPais) values ('Anguilla');
insert into mtPaises (nmPais) values ('Antarctica');
insert into mtPaises (nmPais) values ('Antigua &amp; Barbud');
insert into mtPaises (nmPais) values ('Argentina');
insert into mtPaises (nmPais) values ('Armenia');
insert into mtPaises (nmPais) values ('Aruba');
insert into mtPaises (nmPais) values ('Australia');
insert into mtPaises (nmPais) values ('Austria');
insert into mtPaises (nmPais) values ('Azerbaijan');
insert into mtPaises (nmPais) values ('Bahamas');
insert into mtPaises (nmPais) values ('Bahrain');
insert into mtPaises (nmPais) values ('Bangladesh');
insert into mtPaises (nmPais) values ('Barbados');
insert into mtPaises (nmPais) values ('Belarus');
insert into mtPaises (nmPais) values ('Belgium');
insert into mtPaises (nmPais) values ('Belize');
insert into mtPaises (nmPais) values ('Benin');
insert into mtPaises (nmPais) values ('Bermuda');
insert into mtPaises (nmPais) values ('Bhutan');
insert into mtPaises (nmPais) values ('Bolivia');
insert into mtPaises (nmPais) values ('Bosnia &amp; Herzeg..');
insert into mtPaises (nmPais) values ('Botswana');
insert into mtPaises (nmPais) values ('Bouvet Island');
insert into mtPaises (nmPais) values ('Brazil');
insert into mtPaises (nmPais) values ('British Indian Ocea');
insert into mtPaises (nmPais) values ('Brunei Darussalam');
insert into mtPaises (nmPais) values ('Bulgaria');
insert into mtPaises (nmPais) values ('Burkina Faso');
insert into mtPaises (nmPais) values ('Burundi');
insert into mtPaises (nmPais) values ('Cambodia');
insert into mtPaises (nmPais) values ('Cameroon');
insert into mtPaises (nmPais) values ('Canada');
insert into mtPaises (nmPais) values ('Cape Verde');
insert into mtPaises (nmPais) values ('Cayman Islands');
insert into mtPaises (nmPais) values ('Central African Rep');
insert into mtPaises (nmPais) values ('Chad');
insert into mtPaises (nmPais) values ('Chile');
insert into mtPaises (nmPais) values ('China');
insert into mtPaises (nmPais) values ('Christmas Island');
insert into mtPaises (nmPais) values ('Cocos (Keeling) Isl');
insert into mtPaises (nmPais) values ('Colombia');
insert into mtPaises (nmPais) values ('Comoros');
insert into mtPaises (nmPais) values ('Congo');
insert into mtPaises (nmPais) values ('Cook Islands');
insert into mtPaises (nmPais) values ('Costa Rica');
insert into mtPaises (nmPais) values ('Cote DIvoire');
insert into mtPaises (nmPais) values ('Croatia (Hrvatska');
insert into mtPaises (nmPais) values ('Cuba');
insert into mtPaises (nmPais) values ('Cyprus');
insert into mtPaises (nmPais) values ('Czech Republic');
insert into mtPaises (nmPais) values ('Denmark');
insert into mtPaises (nmPais) values ('Djibouti');
insert into mtPaises (nmPais) values ('Dominica');
insert into mtPaises (nmPais) values ('Dominican Rep');
insert into mtPaises (nmPais) values ('East Timor');
insert into mtPaises (nmPais) values ('Ecuador');
insert into mtPaises (nmPais) values ('Egypt');
insert into mtPaises (nmPais) values ('El Salvador');
insert into mtPaises (nmPais) values ('Equatorial Guinea');
insert into mtPaises (nmPais) values ('Eritrea');
insert into mtPaises (nmPais) values ('Estonia');
insert into mtPaises (nmPais) values ('Ethiopia');
insert into mtPaises (nmPais) values ('Falkland Island');
insert into mtPaises (nmPais) values ('Faroe Islands');
insert into mtPaises (nmPais) values ('Fiji');
insert into mtPaises (nmPais) values ('Finland');
insert into mtPaises (nmPais) values ('France');
insert into mtPaises (nmPais) values ('France, Metropolitan');
insert into mtPaises (nmPais) values ('French Guiana');
insert into mtPaises (nmPais) values ('French Polynesia');
insert into mtPaises (nmPais) values ('French Southern terr');
insert into mtPaises (nmPais) values ('Gabon');
insert into mtPaises (nmPais) values ('Gambia');
insert into mtPaises (nmPais) values ('Georgia');
insert into mtPaises (nmPais) values ('Germany');
insert into mtPaises (nmPais) values ('Ghana');
insert into mtPaises (nmPais) values ('Gibraltar');
insert into mtPaises (nmPais) values ('Greece');
insert into mtPaises (nmPais) values ('Greenland');
insert into mtPaises (nmPais) values ('Grenada');
insert into mtPaises (nmPais) values ('Guadeloupe');
insert into mtPaises (nmPais) values ('Guam');
insert into mtPaises (nmPais) values ('Guatemala');
insert into mtPaises (nmPais) values ('Guinea');
insert into mtPaises (nmPais) values ('Guinea-Bissau');
insert into mtPaises (nmPais) values ('Guyana');
insert into mtPaises (nmPais) values ('Haiti');
insert into mtPaises (nmPais) values ('Heard &amp; Mc Donald');
insert into mtPaises (nmPais) values ('Honduras');
insert into mtPaises (nmPais) values ('Hong Kong');
insert into mtPaises (nmPais) values ('Hungary');
insert into mtPaises (nmPais) values ('Iceland');
insert into mtPaises (nmPais) values ('India');
insert into mtPaises (nmPais) values ('Indonesia');
insert into mtPaises (nmPais) values ('Ira');
insert into mtPaises (nmPais) values ('Iraq');
insert into mtPaises (nmPais) values ('Ireland');
insert into mtPaises (nmPais) values ('Israel');
insert into mtPaises (nmPais) values ('Italy');
insert into mtPaises (nmPais) values ('Jamaica');
insert into mtPaises (nmPais) values ('Japan');
insert into mtPaises (nmPais) values ('Jordan');
insert into mtPaises (nmPais) values ('Kazakhstan');
insert into mtPaises (nmPais) values ('Kenya');
insert into mtPaises (nmPais) values ('Kiribati');
insert into mtPaises (nmPais) values ('Kore');
insert into mtPaises (nmPais) values ('Korea, Republic of');
insert into mtPaises (nmPais) values ('Kuwait');
insert into mtPaises (nmPais) values ('Kyrgyzstan');
insert into mtPaises (nmPais) values ('La');
insert into mtPaises (nmPais) values ('Latvia');
insert into mtPaises (nmPais) values ('Lebanon');
insert into mtPaises (nmPais) values ('Lesotho');
insert into mtPaises (nmPais) values ('Liberia');
insert into mtPaises (nmPais) values ('Libyan Arab Jamahiriya');
insert into mtPaises (nmPais) values ('Liechtenstein');
insert into mtPaises (nmPais) values ('Lithuania');
insert into mtPaises (nmPais) values ('Luxembourg');
insert into mtPaises (nmPais) values ('Macau');
insert into mtPaises (nmPais) values ('Macedoni');
insert into mtPaises (nmPais) values ('Madagascar');
insert into mtPaises (nmPais) values ('Malawi');
insert into mtPaises (nmPais) values ('Malaysia');
insert into mtPaises (nmPais) values ('Maldives');
insert into mtPaises (nmPais) values ('Mali');
insert into mtPaises (nmPais) values ('Malta');
insert into mtPaises (nmPais) values ('Marshall Islands');
insert into mtPaises (nmPais) values ('Martinique');
insert into mtPaises (nmPais) values ('Mauritania');
insert into mtPaises (nmPais) values ('Mauritius');
insert into mtPaises (nmPais) values ('Mayotte');
insert into mtPaises (nmPais) values ('Mexico');
insert into mtPaises (nmPais) values ('Micronesi');
insert into mtPaises (nmPais) values ('Moldov');
insert into mtPaises (nmPais) values ('Monaco');
insert into mtPaises (nmPais) values ('Mongolia');
insert into mtPaises (nmPais) values ('Montserrat');
insert into mtPaises (nmPais) values ('Morocco');
insert into mtPaises (nmPais) values ('Mozambique');
insert into mtPaises (nmPais) values ('Myanmar');
insert into mtPaises (nmPais) values ('Namibia');
insert into mtPaises (nmPais) values ('Nauru');
insert into mtPaises (nmPais) values ('Nepal');
insert into mtPaises (nmPais) values ('Netherlands');
insert into mtPaises (nmPais) values ('Netherlands Antilles');
insert into mtPaises (nmPais) values ('New Caledonia');
insert into mtPaises (nmPais) values ('New Zealand');
insert into mtPaises (nmPais) values ('Nicaragua');
insert into mtPaises (nmPais) values ('Niger');
insert into mtPaises (nmPais) values ('Nigeria');
insert into mtPaises (nmPais) values ('Niue');
insert into mtPaises (nmPais) values ('Norfolk Island');
insert into mtPaises (nmPais) values ('Northern Mariana Islands');
insert into mtPaises (nmPais) values ('Norway');
insert into mtPaises (nmPais) values ('Oman');
insert into mtPaises (nmPais) values ('Pakistan');
insert into mtPaises (nmPais) values ('Palau');
insert into mtPaises (nmPais) values ('Panama');
insert into mtPaises (nmPais) values ('Papua New Guinea');
insert into mtPaises (nmPais) values ('Paraguay');
insert into mtPaises (nmPais) values ('Peru');
insert into mtPaises (nmPais) values ('Philippines');
insert into mtPaises (nmPais) values ('Pitcairn');
insert into mtPaises (nmPais) values ('Poland');
insert into mtPaises (nmPais) values ('Portugal');
insert into mtPaises (nmPais) values ('Puerto Rico');
insert into mtPaises (nmPais) values ('Qatar');
insert into mtPaises (nmPais) values ('Reunion');
insert into mtPaises (nmPais) values ('Romania');
insert into mtPaises (nmPais) values ('Russian Federation');
insert into mtPaises (nmPais) values ('Rwanda');
insert into mtPaises (nmPais) values ('Saint Kitts and Nevis');
insert into mtPaises (nmPais) values ('Saint Lucia');
insert into mtPaises (nmPais) values ('Saint Vincent &amp; Grenadine');
insert into mtPaises (nmPais) values ('Samoa');
insert into mtPaises (nmPais) values ('San Marino');
insert into mtPaises (nmPais) values ('Sao Tome and Principe');
insert into mtPaises (nmPais) values ('Saudi Arabia');
insert into mtPaises (nmPais) values ('Senegal');
insert into mtPaises (nmPais) values ('Seychelles');
insert into mtPaises (nmPais) values ('Sierra Leone');
insert into mtPaises (nmPais) values ('Singapore');
insert into mtPaises (nmPais) values ('Slovakia (Slovak Rep');
insert into mtPaises (nmPais) values ('Slovenia');
insert into mtPaises (nmPais) values ('Solomon Islands');
insert into mtPaises (nmPais) values ('Somalia');
insert into mtPaises (nmPais) values ('South Africa');
insert into mtPaises (nmPais) values ('Spain');
insert into mtPaises (nmPais) values ('Sri Lanka');
insert into mtPaises (nmPais) values ('St. Helena');
insert into mtPaises (nmPais) values ('St. Pierre and Miquelon');
insert into mtPaises (nmPais) values ('Sudan');
insert into mtPaises (nmPais) values ('SurinmPais');
insert into mtPaises (nmPais) values ('Svalbard Jan Maye');
insert into mtPaises (nmPais) values ('Swaziland');
insert into mtPaises (nmPais) values ('lue="SE">Swede');
insert into mtPaises (nmPais) values ('Switzerland');
insert into mtPaises (nmPais) values ('Syrian Arab Republic');
insert into mtPaises (nmPais) values ('Taiwan');
insert into mtPaises (nmPais) values ('Tajikistan');
insert into mtPaises (nmPais) values ('Tanzani');
insert into mtPaises (nmPais) values ('Thailand');
insert into mtPaises (nmPais) values ('Togo');
insert into mtPaises (nmPais) values ('Tokelau');
insert into mtPaises (nmPais) values ('Tonga');
insert into mtPaises (nmPais) values ('Trinidad and Tobago');
insert into mtPaises (nmPais) values ('Tunisia');
insert into mtPaises (nmPais) values ('Turkey');
insert into mtPaises (nmPais) values ('Turkmenistan');
insert into mtPaises (nmPais) values ('Turks &amp; Caicos Island');
insert into mtPaises (nmPais) values ('Tuvalu');
insert into mtPaises (nmPais) values ('Uganda');
insert into mtPaises (nmPais) values ('Ukraine');
insert into mtPaises (nmPais) values ('United Arab Emirates');
insert into mtPaises (nmPais) values ('United Kingdom');
insert into mtPaises (nmPais) values ('United State');
insert into mtPaises (nmPais) values ('United States Minor Island');
insert into mtPaises (nmPais) values ('Uruguay');
insert into mtPaises (nmPais) values ('Uzbekistan');
insert into mtPaises (nmPais) values ('Vanuatu');
insert into mtPaises (nmPais) values ('Vatican City Stat');
insert into mtPaises (nmPais) values ('Venezuela');
insert into mtPaises (nmPais) values ('Viet NAM');
insert into mtPaises (nmPais) values ('Virgin Islands (British)');
insert into mtPaises (nmPais) values ('Virgin Islands (U.S.)');
insert into mtPaises (nmPais) values ('Wallis &amp; Futuna Island');
insert into mtPaises (nmPais) values ('Western Sahara');
insert into mtPaises (nmPais) values ('Yemen');
insert into mtPaises (nmPais) values ('Yugoslavia');
insert into mtPaises (nmPais) values ('Zaire');
insert into mtPaises (nmPais) values ('Zambia');
insert into mtPaises (nmPais) values ('Zimbabwe');
commit;